services:
  mem0-postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mem0-pgdata:/var/lib/postgresql/data

  mem0:
    image: sxkiss/mem0
    restart: unless-stopped
    depends_on:
      mem0-postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: mem0-postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      HTTPS_PROXY: http://172.17.0.1:7890
      HTTP_PROXY: http://172.17.0.1:7890
      HF_HOME: /app/hf_cache
    volumes:
      - mem0-hf_cache:/app/hf_cache
    ports:
      - "8000:8000"

volumes:
  mem0-pgdata:
  mem0-hf_cache: